### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by ghost** [SlowsieNT/SlowsieNT#1]
Hello, if you're alive call me
I don't see activity in session

**Comment by SlowsieNT** [comment]
Hello,
Very much alive, but too busy with irl
Unfortunately I will be able to do projects in a month due holidays and such
Life be like..

**Comment by ghost** [comment]
Understood, okay, I won't distract you, have a good Christmas to you SlowsieNT ))))

**Comment by SlowsieNT** [comment]
Same
